---
abstract: "Check to see that version's in modules are sane"
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Exception: 0
  Test::More: 0.88
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Version
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
provides:
  Test::Version:
    file: lib/Test/Version.pm
    version: 1.002004
requires:
  Carp: 0
  Exporter: 0
  File::Find::Rule::Perl: 0
  Module::Metadata: 0
  Test::Builder: 0
  Test::More: 0.88
  parent: 0
  perl: 5.006
  strict: 0
  version: 0.86
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/test-version/issues
  homepage: https://metacpan.org/dist/Test-Version
  repository: git://github.com/xenoterracide/test-version.git
version: 1.002004
x_contributors:
  - 'Graham Ollis <perl@wdlabs.com>'
  - 'Michael G. Schwern <schwern@pobox.com>'
  - 'Mike Doherty <doherty@cs.dal.ca>'
  - 'particle <particle@cpan.org>'
