---
abstract: 'check for VERSION information in modules'
author:
  - 'particle <particle@cpan.org>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Version
no_index:
  directory:
    - corpus
    - t/version
  file:
    - perlcritic.rc
requires:
  Carp: 0
  Exporter: 5.562
  Test::Builder: 0.17
  perl: 5.006_001
resources:
  bugtracker: http://github.com/xenoterracide/Test-Version/issues
  repository: git://github.com/xenoterracide/Test-Version.git
version: 0.03
